# Generated by Django 5.0.7 on 2024-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='Новая доска', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='columns',
            field=models.ManyToManyField(blank=True, to='board.column'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Новая доска', max_length=255),
        ),
    ]
